name: Deployment

on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      VITE_WEBSOCKET_BASE_URL: ${{ secrets.VITE_WEBSOCKET_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export all secrets to .env file
        run:
          echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" > .env
          echo "VITE_WEBSOCKET_BASE_URL=${VITE_WEBSOCKET_BASE_URL}" >> .env
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync dist/ s3://quizzes-front-end --delete